#name: Deploy user ms from Game House
#
#on:
#  push:
#    branches: [main]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: SetUp Java
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'zulu'
#          java-version: '17'
#
#      - name: Build Project
#        run: mvn clean install -DskipTests
#
#      - name: Login Docker Hub
#        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
#
#      - name: Build Docker image
#        run: docker build -t  ${{secrets.DOCKER_USERNAME}}/user-ms-gh .
#
#      - name: Push image to docker hub
#        run: docker push ${{secrets.DOCKER_USERNAME}}/user-ms-gh
#
#  deploy:
#    needs: build
#    runs-on: self-hosted
#    steps:
#      - name: Pull image from docker hub
#        run: sudo docker pull joeyqpbdev/user-ms-gh:latest
#
#      - name: Remove container if exists
#        run: sudo docker rm -f user-ms-gh-container
#
#      - name: Run docker container
#        run: sudo docker run -d -p 8081:8081 --name user-ms-gh-container joeyqpbdev/user-ms-gh:latest