# name: Build for Multiple Spring Boot Apps

# on:
#   push:
#     branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: SetUp Java
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'zulu'
#           java-version: '17'

#       - name: Build Project user-service
#         run: mvn clean install -DskipTests
#         working-directory: ./gamehouse-user-service

#       - name: Build Project sugestion-service
#         run: mvn clean install -DskipTests
#         working-directory: ./gamehouse-sugestion-service

#       - name: Build Project api-gateway
#         run: mvn clean install -DskipTests
#         working-directory: ./gamehouse-api-gateway

#       - name: Build Project email
#         run: mvn clean install -DskipTests
#         working-directory: ./email

#       - name: Build Project sendEmail
#         run: mvn clean install -DskipTests
#         working-directory: ./gamehouse-sendEmail-service          

#       - name: Login Docker Hub
#         run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

#       - name: Build Docker image for user-ms
#         run: docker build -t ${{ secrets.DOCKER_USERNAME }}/user-ms .
#         working-directory: ./gamehouse-user-service

#       - name: Build Docker image for suggestion-ms
#         run: docker build -t ${{ secrets.DOCKER_USERNAME }}/suggestion-ms .
#         working-directory: ./gamehouse-sugestion-service

#       - name: Build Docker image for api-gateway-ms
#         run: docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway-ms .
#         working-directory: ./gamehouse-api-gateway

#       - name: Build Docker image for email-welcome-ms
#         run: docker build -t ${{ secrets.DOCKER_USERNAME }}/email-welcome-ms --build-arg SPRING_MAIL_USERNAME="${{ secrets.SPRING_MAIL_USERNAME }}" --build-arg SPRING_MAIL_PASSWORD="${{ secrets.SPRING_MAIL_PASSWORD }}" .
#         working-directory: ./email

#       - name: Build Docker image for send-email-ms
#         run: docker build -t ${{ secrets.DOCKER_USERNAME }}/send-email-ms  --build-arg AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" --build-arg AWS_SECRET_KEY="${{ secrets.AWS_SECRET_KEY }}" --build-arg AWS_REGION="${{ secrets.AWS_REGION }}" .
#         working-directory: ./gamehouse-sendEmail-service  

#       - name: Push image to docker hub user ms
#         run: docker push ${{ secrets.DOCKER_USERNAME }}/user-ms

#       - name: Push image to docker hub suggestion ms
#         run: docker push ${{ secrets.DOCKER_USERNAME }}/suggestion-ms

#       - name: Push image to docker hub api-gateway ms
#         run: docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway-ms

#       - name: Push image to docker hub email-welcome ms
#         run: docker push ${{ secrets.DOCKER_USERNAME }}/email-welcome-ms

#       - name: Push image to docker hub send-email ms
#         run: docker push ${{ secrets.DOCKER_USERNAME }}/send-email-ms