name: Deploy for Multiple Spring Boot Apps

on:
  workflow_run:
    workflows: ["Build for Multiple Spring Boot Apps"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        project: [user-ms, suggestion-ms, api-gateway-ms, email-welcome-ms, send-email-ms]

      - name: Stop App if running
        run: |
          if [ -f /home/ubuntu/apps/docker-compose.yml ]; then
            if sudo docker-compose -f /home/ubuntu/apps/docker-compose.yml ps -q | grep -q .; then
              sudo docker-compose -f /home/ubuntu/apps/docker-compose.yml down
            fi
          fi

      - name: Remove container if exists
        run: sudo docker rm -f ${{ matrix.project }}-container

      - name: remove old images
        run: sudo docker rmi -f ${{ matrix.project }}:latest

      - name: remove old images
        run: sudo docker images | grep '^${{ matrix.project }} ' | awk '{print $3}' | xargs sudo docker rmi -f
 
      - name: Pull image from docker hub
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ matrix.project }}:latest