name: Deploy for Multiple Spring Boot Apps

on:
  workflow_run:
    workflows: ["Build for Multiple Spring Boot Apps"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        project: [user-ms, suggestion-ms, api-gateway-ms, email-welcome-ms, send-email-ms]
    steps:
      - name: Stop App
        run: sudo docker-compose -f /home/ubuntu/apps/docker-compose.yml down

      - name: Remove container if exists
        run: sudo docker rm -f ${{ matrix.project }}-container

      - name: remove old images
        run: docker rmi ${{ matrix.project }}:latest

      - name: Pull image from docker hub
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ matrix.project }}:latest