name: Up Application

on:
  workflow_run:
    workflows: ["Deploy for Multiple Spring Boot Apps"]
    types:
      - completed

jobs:
  docker-compose:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Remove existing docker-compose.yml if exists
        run: |
          if [ -f /home/ubuntu/apps/docker-compose.yml ]; then
            sudo docker-compose -f /home/ubuntu/apps/docker-compose.yml down
            rm /home/ubuntu/apps/docker-compose.yml
          fi

      - name: Copy docker-compose file
        run: sudo cp ./docker-compose.yml /home/ubuntu/apps/docker-compose.yml

      - name: Deploy Docker Compose stack
        run: sudo docker-compose -f /home/ubuntu/apps/docker-compose.yml up -d
