name: Up Application

on:
  workflow_run:
    workflows: ["Deploy for Multiple Spring Boot Apps"]
    types:
      - completed

jobs:
  docker-compose:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create apps directory if not exists
        run: sudo mkdir -p /home/ubuntu/apps

      - name: Create Docker network if not exists
        run: |
          if [ ! "$(sudo docker network ls | grep gamehouse-net)" ]; then
            sudo docker network create gamehouse-net
          fi

      - name: Remove existing docker-compose.yml if exists
        run: |
          if [ -f /home/ubuntu/apps/docker-compose.yml ]; then
            sudo docker-compose -f /home/ubuntu/apps/docker-compose.yml down
            sudo rm /home/ubuntu/apps/docker-compose.yml
          fi

      - name: Copy docker-compose file
        run: sudo cp docker-compose.yml /home/ubuntu/apps/docker-compose.yml
        working-directory: ${{ github.workspace }}

      - name: Deploy Docker Compose stack
        run: sudo docker-compose -f /home/ubuntu/apps/docker-compose.yml up -d